export type MediaType = "image" | "video" | "audio";
export type Variation = "high" | "compressed" | "thumb" | "blur" | "thumbnail";
export type UsedAs = "Poster" | "Media" | "Preview" | string;

export interface Media {
  _id: string;
  path: string;
  type: MediaType;
  status: string;
  variations: Variation[];
  signature?: Partial<Record<Variation, string>>;
  poster?: {
    _id: string;
    path: string;
    signature?: Partial<Record<Variation, string>>;
    variations: Variation[];
    resolution?: { width: number; height: number };
    moderation_flags: string[];
    is_autogenerated?: boolean;
    signed_urls?: {
      [key in Variation]: string;
    };
  };
  resolution?: { width: number; height: number };
  duration?: number;
  moderation_flags?: string[];
  used_as: UsedAs;
  signed_urls?: {
    [key in Variation]: string;
  };
}
